# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Configure.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConfigForm(object):
    def setupUi(self, ConfigForm):
        ConfigForm.setObjectName("ConfigForm")
        ConfigForm.setWindowModality(QtCore.Qt.ApplicationModal)
        ConfigForm.resize(640, 363)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ICON/ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ConfigForm.setWindowIcon(icon)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(ConfigForm)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.Config_tabWidget = QtWidgets.QTabWidget(ConfigForm)
        self.Config_tabWidget.setObjectName("Config_tabWidget")
        self.MySQL_Tab = QtWidgets.QWidget()
        self.MySQL_Tab.setObjectName("MySQL_Tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.MySQL_Tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.MySQL_Tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(self.MySQL_Tab)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(self.MySQL_Tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.label_4 = QtWidgets.QLabel(self.MySQL_Tab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.label_5 = QtWidgets.QLabel(self.MySQL_Tab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.IP_lineEdit = QtWidgets.QLineEdit(self.MySQL_Tab)
        self.IP_lineEdit.setObjectName("IP_lineEdit")
        self.verticalLayout.addWidget(self.IP_lineEdit)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.User_lineEdit = QtWidgets.QLineEdit(self.MySQL_Tab)
        self.User_lineEdit.setObjectName("User_lineEdit")
        self.verticalLayout.addWidget(self.User_lineEdit)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.Password_lineEdit = QtWidgets.QLineEdit(self.MySQL_Tab)
        self.Password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_lineEdit.setObjectName("Password_lineEdit")
        self.verticalLayout.addWidget(self.Password_lineEdit)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.DataBase_lineEdit = QtWidgets.QLineEdit(self.MySQL_Tab)
        self.DataBase_lineEdit.setObjectName("DataBase_lineEdit")
        self.verticalLayout.addWidget(self.DataBase_lineEdit)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.Table_lineEdit = QtWidgets.QLineEdit(self.MySQL_Tab)
        self.Table_lineEdit.setObjectName("Table_lineEdit")
        self.verticalLayout.addWidget(self.Table_lineEdit)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem15)
        self.MySQLSAVE_pushButton = QtWidgets.QPushButton(self.MySQL_Tab)
        self.MySQLSAVE_pushButton.setObjectName("MySQLSAVE_pushButton")
        self.verticalLayout_3.addWidget(self.MySQLSAVE_pushButton)
        self.MySQLLOAD_pushButton = QtWidgets.QPushButton(self.MySQL_Tab)
        self.MySQLLOAD_pushButton.setObjectName("MySQLLOAD_pushButton")
        self.verticalLayout_3.addWidget(self.MySQLLOAD_pushButton)
        self.MySQLOK_pushButton = QtWidgets.QPushButton(self.MySQL_Tab)
        self.MySQLOK_pushButton.setObjectName("MySQLOK_pushButton")
        self.verticalLayout_3.addWidget(self.MySQLOK_pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.Config_tabWidget.addTab(self.MySQL_Tab, "")
        self.Table_Tab = QtWidgets.QWidget()
        self.Table_Tab.setObjectName("Table_Tab")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.Table_Tab)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem16)
        self.TableRe_Btn = QtWidgets.QPushButton(self.Table_Tab)
        self.TableRe_Btn.setObjectName("TableRe_Btn")
        self.horizontalLayout_9.addWidget(self.TableRe_Btn)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem17)
        self.TableOK_Btn = QtWidgets.QPushButton(self.Table_Tab)
        self.TableOK_Btn.setObjectName("TableOK_Btn")
        self.horizontalLayout_9.addWidget(self.TableOK_Btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.gridLayout.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        self.Table_tableWidget = QtWidgets.QTableWidget(self.Table_Tab)
        self.Table_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Table_tableWidget.setObjectName("Table_tableWidget")
        self.Table_tableWidget.setColumnCount(26)
        self.Table_tableWidget.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Table_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_tableWidget.setHorizontalHeaderItem(25, item)
        self.Table_tableWidget.verticalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.Table_tableWidget, 0, 0, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout)
        self.Config_tabWidget.addTab(self.Table_Tab, "")
        self.Var_Tab = QtWidgets.QWidget()
        self.Var_Tab.setObjectName("Var_Tab")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.Var_Tab)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.Var_Tab)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 140))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 20, 192, 108))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem18)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem19)
        self.X1_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.X1_comboBox.setMinimumSize(QtCore.QSize(76, 20))
        self.X1_comboBox.setObjectName("X1_comboBox")
        self.horizontalLayout_2.addWidget(self.X1_comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem20)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem21)
        self.X2_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.X2_comboBox.setMinimumSize(QtCore.QSize(76, 20))
        self.X2_comboBox.setObjectName("X2_comboBox")
        self.horizontalLayout_3.addWidget(self.X2_comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem22)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem23)
        self.X3_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.X3_comboBox.setMinimumSize(QtCore.QSize(76, 20))
        self.X3_comboBox.setObjectName("X3_comboBox")
        self.horizontalLayout_4.addWidget(self.X3_comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem24)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem25)
        self.X4_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.X4_comboBox.setMinimumSize(QtCore.QSize(76, 20))
        self.X4_comboBox.setObjectName("X4_comboBox")
        self.horizontalLayout_5.addWidget(self.X4_comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.groupBox)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem26)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Var_Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(53, 30, 190, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem27)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem28)
        self.Y_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.Y_comboBox.setMinimumSize(QtCore.QSize(76, 20))
        self.Y_comboBox.setObjectName("Y_comboBox")
        self.horizontalLayout_6.addWidget(self.Y_comboBox)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem29)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem30)
        self.VarApply_pushButton = QtWidgets.QPushButton(self.Var_Tab)
        self.VarApply_pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.VarApply_pushButton.setObjectName("VarApply_pushButton")
        self.horizontalLayout_8.addWidget(self.VarApply_pushButton)
        self.VarOK_pushButton = QtWidgets.QPushButton(self.Var_Tab)
        self.VarOK_pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.VarOK_pushButton.setObjectName("VarOK_pushButton")
        self.horizontalLayout_8.addWidget(self.VarOK_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_7)
        self.Config_tabWidget.addTab(self.Var_Tab, "")
        self.horizontalLayout_12.addWidget(self.Config_tabWidget)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem31)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem32)
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)

        self.retranslateUi(ConfigForm)
        self.Config_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ConfigForm)

    def retranslateUi(self, ConfigForm):
        _translate = QtCore.QCoreApplication.translate
        ConfigForm.setWindowTitle(_translate("ConfigForm", "配置"))
        self.label_2.setText(_translate("ConfigForm", "IP地址："))
        self.label.setText(_translate("ConfigForm", "用户名："))
        self.label_3.setText(_translate("ConfigForm", "密  码："))
        self.label_4.setText(_translate("ConfigForm", "库名称："))
        self.label_5.setText(_translate("ConfigForm", "表单名："))
        self.IP_lineEdit.setInputMask(_translate("ConfigForm", "000.0.0.0"))
        self.IP_lineEdit.setText(_translate("ConfigForm", "127.0.0.1"))
        self.User_lineEdit.setText(_translate("ConfigForm", "root"))
        self.Password_lineEdit.setText(_translate("ConfigForm", "123456"))
        self.Password_lineEdit.setPlaceholderText(_translate("ConfigForm", "Enter Password"))
        self.DataBase_lineEdit.setText(_translate("ConfigForm", "data"))
        self.DataBase_lineEdit.setPlaceholderText(_translate("ConfigForm", "Enter DataBaseName"))
        self.Table_lineEdit.setText(_translate("ConfigForm", "flowdata"))
        self.Table_lineEdit.setPlaceholderText(_translate("ConfigForm", "Enter TableName"))
        self.MySQLSAVE_pushButton.setText(_translate("ConfigForm", "保存配置"))
        self.MySQLLOAD_pushButton.setText(_translate("ConfigForm", "加载配置"))
        self.MySQLOK_pushButton.setText(_translate("ConfigForm", "确定"))
        self.MySQLOK_pushButton.setShortcut(_translate("ConfigForm", "Return"))
        self.Config_tabWidget.setTabText(self.Config_tabWidget.indexOf(self.MySQL_Tab), _translate("ConfigForm", "MySQL配置"))
        self.TableRe_Btn.setText(_translate("ConfigForm", "刷新"))
        self.TableOK_Btn.setText(_translate("ConfigForm", "确定"))
        self.TableOK_Btn.setShortcut(_translate("ConfigForm", "Return"))
        item = self.Table_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("ConfigForm", "New Row"))
        item = self.Table_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("ConfigForm", "New Row"))
        item = self.Table_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("ConfigForm", "New Row"))
        item = self.Table_tableWidget.verticalHeaderItem(3)
        item.setText(_translate("ConfigForm", "New Row"))
        item = self.Table_tableWidget.verticalHeaderItem(4)
        item.setText(_translate("ConfigForm", "New Row"))
        item = self.Table_tableWidget.verticalHeaderItem(5)
        item.setText(_translate("ConfigForm", "New Row"))
        item = self.Table_tableWidget.verticalHeaderItem(6)
        item.setText(_translate("ConfigForm", "New Row"))
        item = self.Table_tableWidget.verticalHeaderItem(7)
        item.setText(_translate("ConfigForm", "New Row"))
        item = self.Table_tableWidget.verticalHeaderItem(8)
        item.setText(_translate("ConfigForm", "New Row"))
        item = self.Table_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(23)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(24)
        item.setText(_translate("ConfigForm", "New Column"))
        item = self.Table_tableWidget.horizontalHeaderItem(25)
        item.setText(_translate("ConfigForm", "New Column"))
        self.Config_tabWidget.setTabText(self.Config_tabWidget.indexOf(self.Table_Tab), _translate("ConfigForm", "表单预览"))
        self.groupBox.setTitle(_translate("ConfigForm", "变量 X"))
        self.label_6.setText(_translate("ConfigForm", "X1"))
        self.label_7.setText(_translate("ConfigForm", "X2"))
        self.label_8.setText(_translate("ConfigForm", "X3"))
        self.label_9.setText(_translate("ConfigForm", "X4"))
        self.groupBox_2.setTitle(_translate("ConfigForm", "变量 Y"))
        self.label_13.setText(_translate("ConfigForm", "Y"))
        self.VarApply_pushButton.setText(_translate("ConfigForm", "应用"))
        self.VarOK_pushButton.setText(_translate("ConfigForm", "确定"))
        self.VarOK_pushButton.setShortcut(_translate("ConfigForm", "Return"))
        self.Config_tabWidget.setTabText(self.Config_tabWidget.indexOf(self.Var_Tab), _translate("ConfigForm", "选择变量"))

import Resource_rc
