# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1296, 706)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ICON/ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.verticalLayout.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1296, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_4 = QtWidgets.QMenu(self.menuFile)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ICON/NEW.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_4.setIcon(icon1)
        self.menu_4.setObjectName("menu_4")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menu)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ICON/VIEW.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_3.setIcon(icon2)
        self.menu_3.setObjectName("menu_3")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_3 = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ICON/SAVE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_3.setIcon(icon3)
        self.action_3.setObjectName("action_3")
        self.action_6 = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ICON/EXPAND.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_6.setIcon(icon4)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ICON/STACK.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_7.setIcon(icon5)
        self.action_7.setObjectName("action_7")
        self.actionabout = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/ICON/ABOUT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionabout.setIcon(icon6)
        self.actionabout.setObjectName("actionabout")
        self.action_8 = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/ICON/ANALYSE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_8.setIcon(icon7)
        self.action_8.setObjectName("action_8")
        self.action = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/ICON/EXIT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action.setIcon(icon8)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/ICON/CONFIG.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_2.setIcon(icon9)
        self.action_2.setObjectName("action_2")
        self.menu_4.addAction(self.action_8)
        self.menuFile.addAction(self.menu_4.menuAction())
        self.menuFile.addAction(self.action_3)
        self.menuFile.addAction(self.action)
        self.menu_3.addAction(self.action_6)
        self.menu_3.addAction(self.action_7)
        self.menu.addAction(self.menu_3.menuAction())
        self.menu_2.addAction(self.actionabout)
        self.menu_5.addAction(self.action_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.toolBar.addAction(self.action_3)
        self.toolBar.addAction(self.action_8)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_6)
        self.toolBar.addAction(self.action_7)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_2)
        self.toolBar.addAction(self.actionabout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RASO"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.menu_4.setTitle(_translate("MainWindow", "新建"))
        self.menu.setTitle(_translate("MainWindow", "视图"))
        self.menu_3.setTitle(_translate("MainWindow", "窗口显示"))
        self.menu_2.setTitle(_translate("MainWindow", "关于"))
        self.menu_5.setTitle(_translate("MainWindow", "工程"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_3.setText(_translate("MainWindow", "保存"))
        self.action_3.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_6.setText(_translate("MainWindow", "平铺"))
        self.action_7.setText(_translate("MainWindow", "层叠"))
        self.actionabout.setText(_translate("MainWindow", "关于..."))
        self.actionabout.setIconText(_translate("MainWindow", "关于..."))
        self.action_8.setText(_translate("MainWindow", "在线分析"))
        self.action_8.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action.setText(_translate("MainWindow", "退出"))
        self.action.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.action_2.setText(_translate("MainWindow", "配置"))
        self.action_2.setShortcut(_translate("MainWindow", "Ctrl+C"))

import Resource_rc
